name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http_parser: ^4.0.0
  file_picker: ^8.1.2
  path_provider: ^2.0.11
  permission_handler: ^11.0.1
  logging: ^1.0.2
  http: ^1.2.2
  pdf: ^3.8.0
  shared_preferences: ^2.0.15
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  flutter_plugin_android_lifecycle: 2.0.22

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/OCR-Software.jpg
    - lib/assets/QuickScan.png
    - lib/assets/logobaner.png
    - lib/assets/app_icon.png
